#!/bin/bash
# Script 5: Philosophy Generator
# Author: Student Analyst | Course: Open Source Software

# --- Variables ---
STUDENT_NAME="Student Analyst"
SOFTWARE_CHOICE="Python"
OUTPUT_FILE="manifesto_report.txt"

echo "=== Philosophy Generator for $SOFTWARE_CHOICE ==="

# We use /dev/tty to ensure 'read' waits for user input even if we redirect output later
echo "Question 1: Please enter your favorite $SOFTWARE_CHOICE feature (e.g., 'Readability'):"
read -r feature < /dev/tty
feature=${feature:-"Readability"}

echo "Question 2: What is your core value for open source? (e.g., 'Transparency', 'Community'):"
read -r value < /dev/tty
value=${value:-"Transparency"}

echo "Question 3: What represents your programming approach? (e.g., 'Simplicity', 'Efficiency'):"
read -r approach < /dev/tty
approach=${approach:-"Simplicity"}

# --- The "Capture" Block ---
# Everything inside the curly braces { } is sent to both the screen AND the file
{
    echo "        OPEN SOURCE MANIFESTO"
    
    echo "We believe in the power of open collaboration,"
    echo "guided by $feature and driven by $value."
    echo ""
    echo "Inspired by $SOFTWARE_CHOICE's design principles, we pledge to:"
    echo "1. Foster a culture of $value."
    echo "2. Keep code accessible by maintaining $approach."
    echo "3. Remember that $approach over complexity is key."
    
    echo "Generated by: $STUDENT_NAME"
    echo "Date: $(date)"
} | tee "$OUTPUT_FILE"

echo ""
echo ">>> Success! Your manifesto has been saved to: $(pwd)/$OUTPUT_FILE"
